#!/bin/bash

openfire_deb_name="openfire_4.9.2_all.deb"

# --------------------------------------------------
# 解析參數
# --------------------------------------------------
# 如果沒有提供參數，則顯示錯誤訊息
if [ $# -eq 0 ]; then
  echo
  echo "Error: No domain provided."
  echo "Usage: $(basename $0) your_domain"
  echo
  exit 1
fi

domain=$1


# --------------------------------------------------
# 申請 SSL 憑證
# --------------------------------------------------
# 確認是否 nslookup 查的 IP 位址為本機 IP
ip=$(nslookup $domain | grep 'Address:' | tail -n1 | awk '{print $2}')
if [ "$ip" != "$(curl ipinfo.io/ip)" ]; then
  echo
  echo "Error: The domain $domain does not resolve to this machine's IP address."
  echo
  exit 1
fi

# 申請 Let's Encrypt 憑證
echo "Requesting Let's Encrypt certificate for $domain..."
sudo apt install certbot -y
sudo ufw allow http
sudo certbot certonly --standalone -d $domain --non-interactive --agree-tos --register-unsafely-without-email


# --------------------------------------------------
# 開始安裝
# --------------------------------------------------
# 安裝 JAVA
echo
echo "Installing Java..."
sudo apt install default-jre -y

# 安裝 Openfire
echo
echo "Installing Openfire..."
wget https://www.igniterealtime.org/downloadServlet?filename=openfire/$openfire_deb_name -O $openfire_deb_name
sudo dpkg -i $openfire_deb_name
sudo apt install -f -y
sudo rm $openfire_deb_name

# --------------------------------------------------
# 啟動前設定
# --------------------------------------------------
# 開啟防火牆
echo
echo "Configuring firewall..."
# for admin console
sudo ufw allow 9091/tcp
# for xmpp
sudo ufw allow 5222,5223/tcp
# for http binding, file transfer
sudo ufw allow 7443/tcp
sudo ufw reload

# disable port 9090
sed -i 's/<port>9090<\/port>/<port>-1<\/port>/' /usr/share/openfire/conf/openfire.xml

# 更新 Keystore
mkdir k.tmp
cd k.tmp
sudo cp /etc/letsencrypt/live/$domain/fullchain.pem fullchain.pem
sudo cp /etc/letsencrypt/live/$domain/privkey.pem privkey.pem
sudo openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out openfire.p12 -name openfire -password pass:changeit
sudo keytool -importkeystore -srckeystore openfire.p12 -srcstoretype PKCS12 -destkeystore /usr/share/openfire/resources/security/keystore -deststoretype JKS -srcstorepass changeit -deststorepass changeit
cd ..
rm -rf k.tmp
sudo cp renew_letsencrypt_cert /etc/letsencrypt/renew_letsencrypt_cert
sudo chmod 755 /etc/letsencrypt/renew_letsencrypt_cert

# --------------------------------------------------
# 啟動
# --------------------------------------------------
# 啟動 Openfire
echo
echo "Starting Openfire..."
sudo systemctl start openfire
sudo systemctl enable openfire
echo

# --------------------------------------------------
# 啟用 fail2ban
# --------------------------------------------------
# 安裝 fail2ban
echo
echo "Installing fail2ban..."
sudo apt install fail2ban -y

# 啟動 fail2ban
sudo systemctl start fail2ban
sudo systemctl enable fail2ban

# 設定 fail2ban
sudo cat <<EOF >> /etc/fail2ban/jail.local
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1
bantime = 7d
findtime = 10m
maxretry = 3

[sshd]
port    = ssh
backend = %(sshd_backend)s
enabled = true
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7d
findtime = 10m

[ufw]
enabled = true
filter = ufw.aggressive
action = iptables-allports
logpath = /var/log/ufw.log
maxretry = 3
bantime = 7d
findtime = 10m
EOF

sudo cat <<EOF >> /etc/fail2ban/filter.d/ufw.aggressive.conf
[Definition]
failregex = [UFW BLOCK].+SRC=<HOST> DST
ignoreregex =
EOF

# reload fail2ban
sudo systemctl reload fail2ban
sudo systemctl restart fail2ban

# --------------------------------------------------
# 架設 coturn
# --------------------------------------------------
# 安裝 coturn
sudo apt install coturn -y
sudo mkdir -p /etc/coturn
sudo cp /etc/letsencrypt/live/$domain/fullchain.pem /etc/coturn/fullchain.pem
sudo cp /etc/letsencrypt/live/$domain/privkey.pem /etc/coturn/privkey.pem

# generate password
turn_pwd=$(openssl rand -base64 12)

# 修改 /etc/turnserver.conf
sudo cat <<EOF >> /etc/turnserver.conf
listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350
external-ip=$ip
fingerprint
lt-cred-mech
server-name=$domain
user=openfire:$turn_pwd
realm=$domain
cert=/etc/coturn/cert.pem
pkey=/etc/coturn/privkey.pem
cipher-list="DEFAULT"
log-file=/var/log/turnserver.log
simple-log
verbose
TURNSERVER_ENABLED=1
EOF

# uncomment `TURNSERVER_ENABLED=1` at /etc/default/coturn
sudo sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# add turn admin user 
sudo turnadmin -a -u openfire -r $domain -p $turn_pwd

# allow port
sudo ufw allow 3478

# start coturn
echo
echo "Starting coturn..."
sudo systemctl start coturn
sudo systemctl enable coturn
echo

echo
echo "[INFO] Openfire and coturn is running."
echo "[INFO] You need to configure Openfire admin console."
echo "[INFO] Please visit: https://$domain:9091"
echo "[INFO]"
echo "[INFO] The coturn server credentials is (see /etc/turnserver.conf):"
echo "[INFO] username=openfire"
echo "[INFO] password=$turn_pwd"
echo "[INFO]"
echo
